name: jobs examples

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create an artifact for reuse
        run: echo “Full featured artifact” > build-result.txt
      - uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: build-result.txt
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-result
          path: build-result.txt
      - name: use of artifact created
        run: ls build-result.txt
